def load_lista_acoes_com_opcoes() -> []:
    # html = urlopen("https://opcoes.net.br/opcoes/bovespa")
    # bs = BeautifulSoup(html, 'html.parser')
    acoes = ["ABEV3",
             "AZUL4",
             "B3SA3",
             "BBAS3",
             "BBDC4",
             "BBSE3",
             "BEEF3",
             "BOVA11",
             "BPAC11",
             "BRAP4",
             "BRFS3",
             "BRKM5",
             "BRML3",
             "CASH3",
             "CIEL3",
             "CMIG4",
             "COGN3",
             "CSAN3",
             "CSNA3",
             "CYRE3",
             "EGIE3",
             "ELET3",
             "ELET6",
             "EMBR3",
             "GGBR4",
             "GOAU4",
             "HYPE3",
             "IRBR3",
             "ITSA4",
             "ITUB4",
             "JBSS3",
             "KLBN11",
             "LAME4",
             "LREN3",
             "MGLU3",
             "MRFG3",
             "MULT3",
             "NTCO3",
             "PCAR3",
             "PETR4",
             "PRIO3",
             "RADL3",
             "RAIL3",
             "RENT3",
             "SBSP3",
             "SUZB3",
             "TAEE11",
             "UGPA3",
             "USIM5",
             "VALE3",
             "VIIA3",
             "WEGE3",
             "YDUQ3",
             ]
    # items = bs.find_all('select', {'name': 'IdAcao'})[0].findChildren('option')
    # for acao in items[1:]:
    #     acoes.append(acao.text)
    return acoes
